### ISSUE TITLE
Tests for ephys conversion in `nd-data-transfer`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/nd-data-transfer#33]
For example: 
- [x] check that the clipped folder is a valid OE folder
- [x] check that the properties of the OE/Zarr recordings are the same
- [x] etc

**Comment by alejoe91** [comment]
We have tested that the clipped ephys is a valid folder (e.g. in ephys-playground capsule).

For zarr compression, extended tests and improved implementation of the decompression layer in `wavpack-numcodecs==0.1.3` 
solve the previous issue https://github.com/AllenNeuralDynamics/ephys-spikesort-kilosort25-full/issues/2
