### ISSUE TITLE
Update spike sorting capsule to handle compressed data

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/nd-data-transfer#34]
The spike sorting capsule does not work out of the box on compressed data.

### Acceptance Criteria

- [x] `wavpack-numcodecs` is installed
- [x] Address error: `'inter_sample_shift' is not a property!`
- [x] Also: get the capsule pushed to our Github repository

**Comment by alejoe91** [comment]
> The spike sorting capsule does not work out of the box on compressed data.
> 
> ### Acceptance Criteria
> * [x]  `wavpack-numcodecs` is installed
`wavpack-numcodecs` 0.1.2 is now installed and also fixes: https://github.com/AllenNeuralDynamics/ephys-spikesort-kilosort25-full/issues/2

> * [x]  Address error: `'inter_sample_shift' is not a property!`
Fixed on `nd-data-transfer` side by upgrading `probeinterface` to 0.2.11

> * [x]  Also: get the capsule pushed to our Github repository
Here is the capsule: https://github.com/AllenNeuralDynamics/ephys-spikesort-kilosort25-full
